/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Memoria.LNodo;
import Memoria.Lista;
import javax.swing.JPanel;
import eddpractica1.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author JP
 */
public class Carga extends javax.swing.JFrame {

    /**
     * Creates new form Carga
     */
    public Carga() {
        initComponents();
    }
    Lista L;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Componentes = new javax.swing.JPanel();
        Pared = new javax.swing.JPanel();
        LPared = new javax.swing.JLabel();
        ChPared = new javax.swing.JCheckBox();
        ChSuelo = new javax.swing.JCheckBox();
        Suelo = new javax.swing.JPanel();
        LSuelo = new javax.swing.JLabel();
        Goomba = new javax.swing.JPanel();
        LGoomba = new javax.swing.JLabel();
        ChGoomba = new javax.swing.JCheckBox();
        Koopa = new javax.swing.JPanel();
        LKoopa = new javax.swing.JLabel();
        ChKoopa = new javax.swing.JCheckBox();
        Ficha = new javax.swing.JPanel();
        LFicha = new javax.swing.JLabel();
        ChFicha = new javax.swing.JCheckBox();
        ChHongo = new javax.swing.JCheckBox();
        Hongo = new javax.swing.JPanel();
        LHongo = new javax.swing.JLabel();
        Personaje = new javax.swing.JPanel();
        LPersonaje = new javax.swing.JLabel();
        ChPersonaje = new javax.swing.JCheckBox();
        Castillo = new javax.swing.JPanel();
        LCastillo = new javax.swing.JLabel();
        ChCastillo = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        Cargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ACargar = new javax.swing.JPanel();
        Carga = new javax.swing.JLabel();
        PilaCola = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        ACargar1 = new javax.swing.JPanel();
        CargaModificar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreModificar = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Creacion = new javax.swing.JButton();
        Elementos = new javax.swing.JScrollPane();
        Elemento = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Componentes.setBackground(new java.awt.Color(0, 0, 0));

        Pared.setBackground(new java.awt.Color(0, 0, 0));
        Pared.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Pared.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParedMouseClicked(evt);
            }
        });

        LPared.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/muro.png"))); // NOI18N

        javax.swing.GroupLayout ParedLayout = new javax.swing.GroupLayout(Pared);
        Pared.setLayout(ParedLayout);
        ParedLayout.setHorizontalGroup(
            ParedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LPared, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ParedLayout.setVerticalGroup(
            ParedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LPared, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ChPared.setBackground(new java.awt.Color(0, 0, 0));
        ChPared.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChPared.setForeground(new java.awt.Color(255, 255, 255));
        ChPared.setText("Pared");
        ChPared.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChParedItemStateChanged(evt);
            }
        });

        ChSuelo.setBackground(new java.awt.Color(0, 0, 0));
        ChSuelo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChSuelo.setForeground(new java.awt.Color(255, 255, 255));
        ChSuelo.setText("Suelo");
        ChSuelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChSueloItemStateChanged(evt);
            }
        });

        Suelo.setBackground(new java.awt.Color(0, 0, 0));
        Suelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Suelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SueloMouseClicked(evt);
            }
        });

        LSuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/suelo.png"))); // NOI18N

        javax.swing.GroupLayout SueloLayout = new javax.swing.GroupLayout(Suelo);
        Suelo.setLayout(SueloLayout);
        SueloLayout.setHorizontalGroup(
            SueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LSuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SueloLayout.setVerticalGroup(
            SueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LSuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Goomba.setBackground(new java.awt.Color(0, 0, 0));
        Goomba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Goomba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoombaMouseClicked(evt);
            }
        });

        LGoomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/goomba.png"))); // NOI18N

        javax.swing.GroupLayout GoombaLayout = new javax.swing.GroupLayout(Goomba);
        Goomba.setLayout(GoombaLayout);
        GoombaLayout.setHorizontalGroup(
            GoombaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LGoomba, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        GoombaLayout.setVerticalGroup(
            GoombaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LGoomba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ChGoomba.setBackground(new java.awt.Color(0, 0, 0));
        ChGoomba.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChGoomba.setForeground(new java.awt.Color(255, 255, 255));
        ChGoomba.setText("Goomba");
        ChGoomba.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChGoombaItemStateChanged(evt);
            }
        });

        Koopa.setBackground(new java.awt.Color(0, 0, 0));
        Koopa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Koopa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KoopaMouseClicked(evt);
            }
        });

        LKoopa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/koopa.png"))); // NOI18N

        javax.swing.GroupLayout KoopaLayout = new javax.swing.GroupLayout(Koopa);
        Koopa.setLayout(KoopaLayout);
        KoopaLayout.setHorizontalGroup(
            KoopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LKoopa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        KoopaLayout.setVerticalGroup(
            KoopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LKoopa, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        ChKoopa.setBackground(new java.awt.Color(0, 0, 0));
        ChKoopa.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChKoopa.setForeground(new java.awt.Color(255, 255, 255));
        ChKoopa.setText("Koopa");
        ChKoopa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChKoopaItemStateChanged(evt);
            }
        });

        Ficha.setBackground(new java.awt.Color(0, 0, 0));
        Ficha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Ficha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FichaMouseClicked(evt);
            }
        });

        LFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moneda.png"))); // NOI18N

        javax.swing.GroupLayout FichaLayout = new javax.swing.GroupLayout(Ficha);
        Ficha.setLayout(FichaLayout);
        FichaLayout.setHorizontalGroup(
            FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FichaLayout.setVerticalGroup(
            FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ChFicha.setBackground(new java.awt.Color(0, 0, 0));
        ChFicha.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChFicha.setForeground(new java.awt.Color(255, 255, 255));
        ChFicha.setText("Ficha");
        ChFicha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChFichaItemStateChanged(evt);
            }
        });

        ChHongo.setBackground(new java.awt.Color(0, 0, 0));
        ChHongo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChHongo.setForeground(new java.awt.Color(255, 255, 255));
        ChHongo.setText("Hongo");
        ChHongo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChHongoItemStateChanged(evt);
            }
        });

        Hongo.setBackground(new java.awt.Color(0, 0, 0));
        Hongo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Hongo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HongoMouseClicked(evt);
            }
        });

        LHongo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hongo.png"))); // NOI18N

        javax.swing.GroupLayout HongoLayout = new javax.swing.GroupLayout(Hongo);
        Hongo.setLayout(HongoLayout);
        HongoLayout.setHorizontalGroup(
            HongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LHongo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HongoLayout.setVerticalGroup(
            HongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LHongo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Personaje.setBackground(new java.awt.Color(0, 0, 0));
        Personaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Personaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonajeMouseClicked(evt);
            }
        });

        LPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personaje.png"))); // NOI18N
        LPersonaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PersonajeLayout = new javax.swing.GroupLayout(Personaje);
        Personaje.setLayout(PersonajeLayout);
        PersonajeLayout.setHorizontalGroup(
            PersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        PersonajeLayout.setVerticalGroup(
            PersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ChPersonaje.setBackground(new java.awt.Color(0, 0, 0));
        ChPersonaje.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChPersonaje.setForeground(new java.awt.Color(255, 255, 255));
        ChPersonaje.setText("Personaje");
        ChPersonaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChPersonajeItemStateChanged(evt);
            }
        });

        Castillo.setBackground(new java.awt.Color(0, 0, 0));
        Castillo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Castillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CastilloMouseClicked(evt);
            }
        });

        LCastillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/castillo.jpg"))); // NOI18N

        javax.swing.GroupLayout CastilloLayout = new javax.swing.GroupLayout(Castillo);
        Castillo.setLayout(CastilloLayout);
        CastilloLayout.setHorizontalGroup(
            CastilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LCastillo, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        CastilloLayout.setVerticalGroup(
            CastilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LCastillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ChCastillo.setBackground(new java.awt.Color(0, 0, 0));
        ChCastillo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChCastillo.setForeground(new java.awt.Color(255, 255, 255));
        ChCastillo.setText("Castillo");
        ChCastillo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChCastilloItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout ComponentesLayout = new javax.swing.GroupLayout(Componentes);
        Componentes.setLayout(ComponentesLayout);
        ComponentesLayout.setHorizontalGroup(
            ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComponentesLayout.createSequentialGroup()
                        .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ComponentesLayout.createSequentialGroup()
                                .addComponent(ChHongo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ComponentesLayout.createSequentialGroup()
                                .addComponent(ChGoomba, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Goomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ComponentesLayout.createSequentialGroup()
                                .addComponent(ChKoopa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Koopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ComponentesLayout.createSequentialGroup()
                                .addComponent(ChFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Ficha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComponentesLayout.createSequentialGroup()
                        .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChCastillo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChPared, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Suelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Personaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Castillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
        ComponentesLayout.setVerticalGroup(
            ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentesLayout.createSequentialGroup()
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Personaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ChPersonaje)))
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Castillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(ChCastillo)))
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ChPared))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Pared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Suelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(ChSuelo)))
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Goomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(ChGoomba)))
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Koopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ChKoopa)))
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Ficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ChFicha)))
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Hongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ChHongo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Cargar.setText("Cargar");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        jLabel1.setFocusable(false);

        Nombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        ACargar.setBackground(new java.awt.Color(0, 0, 0));
        ACargar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ACargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACargarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ACargarLayout = new javax.swing.GroupLayout(ACargar);
        ACargar.setLayout(ACargarLayout);
        ACargarLayout.setHorizontalGroup(
            ACargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Carga, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        ACargarLayout.setVerticalGroup(
            ACargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Carga, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(ACargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(ACargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        PilaCola.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pila", "Cola" }));
        PilaCola.setSelectedIndex(-1);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        ACargar1.setBackground(new java.awt.Color(0, 0, 0));
        ACargar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ACargar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACargar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ACargar1Layout = new javax.swing.GroupLayout(ACargar1);
        ACargar1.setLayout(ACargar1Layout);
        ACargar1Layout.setHorizontalGroup(
            ACargar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CargaModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        ACargar1Layout.setVerticalGroup(
            ACargar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CargaModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(ACargar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(ACargar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jLabel2.setFocusable(false);

        NombreModificar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Creacion.setText("Creacion de Juego");
        Creacion.setEnabled(false);
        Creacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Creacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreModificar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PilaCola, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PilaCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Creacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Elementos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Elementos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Elemento.setBackground(new java.awt.Color(0, 0, 0));
        Elemento.setLayout(null);
        Elementos.setViewportView(Elemento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Componentes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Componentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Elementos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void ParedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParedMouseClicked
        // TODO add your handling code here:
        if(ChPared.isSelected())
        {
            ChPared.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChPared.setSelected(true);
            Carga.setIcon(LPared.getIcon());
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            ChCastillo.setSelected(false);
        }
        
    }//GEN-LAST:event_ParedMouseClicked

    private void SueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SueloMouseClicked
        // TODO add your handling code here:
        if(ChSuelo.isSelected())
        {
            ChSuelo.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChSuelo.setSelected(true);
            Carga.setIcon(LSuelo.getIcon());
            ChPared.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            ChCastillo.setSelected(false);
        }
    }//GEN-LAST:event_SueloMouseClicked

    public void setLista(Lista l){
        L = l;
    }
    
    int j = 0;
    private void CargarObjetos(){
        if(ChPersonaje.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LPersonaje);
                    }else{
                        L.IngresarFin(Nombre.getText(), LPersonaje);
                    }
                }
            }
        }
        
        if(ChCastillo.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LCastillo);
                    }else{
                        L.IngresarFin(Nombre.getText(), LCastillo);
                    }
                }
            }
        }
        
        if(ChSuelo.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LSuelo);
                    }else{
                        L.IngresarFin(Nombre.getText(), LSuelo);
                    }
                }
            }
        }
        
        
        if(ChPared.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LPared);
                    }else{
                        L.IngresarFin(Nombre.getText(), LPared);
                    }
                }
            }
        }
        
        if(ChGoomba.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LGoomba);
                    }else{
                        L.IngresarFin(Nombre.getText(), LGoomba);
                    }
                }
            }
        }
        
        if(ChKoopa.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LKoopa);
                    }else{
                        L.IngresarFin(Nombre.getText(), LKoopa);
                    }
                }
            }
        }
        
        if(ChHongo.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LHongo);
                    }else{
                        L.IngresarFin(Nombre.getText(), LHongo);
                    }
                }
            }
        }
        
        if(ChFicha.isSelected()){
            if(!"".equals(Nombre.getText()))
            {
                if(PilaCola.getSelectedIndex() != -1)
                {
                    if(PilaCola.getSelectedIndex() == 0)
                    {
                        L.IngresarInicio(Nombre.getText(), LFicha);
                    }else{
                        L.IngresarFin(Nombre.getText(), LFicha);
                    }
                }
            }
        }
        
            Elemento.removeAll();
            
            LNodo aux = L.getInicio();
            int i = 0;
            j = 0;
            while(aux != null){
                aux.setId(j);
                JPanel p = new JPanel();
                JLabel l = new JLabel();
                JLabel la = new JLabel();
                JLabel num = new JLabel();
                p.setLayout(null);
                p.setBounds(15, 15 + i, 168, 65);
                p.setBackground(Color.BLACK);
                p.setBorder(BorderFactory.createLineBorder(Color.WHITE));
                num.setText(""+j);
                l.setText(aux.getNombre());
                l.setForeground(Color.WHITE);
                Font fuente=new Font("Comic Sans MS", Font.PLAIN, 14);
                l.setFont(fuente);
                l.setBounds(58, 5, 80, 50);
                
                JButton boton = new JButton();
                boton.setText("X");
                boton.setBorder(null);
                boton.setBounds(140, 22, 20, 20);
                boton.setBackground(Color.WHITE);
                ActionListener listener = new ActionListener(){ 
                    @Override
                    public void actionPerformed(ActionEvent e) { 
                        System.out.println("nombre: " +l.getText()+ " / j: "+num.getText());
                        L.Eliminar(l.getText(),Integer.parseInt(num.getText()));
                        CargarObjetos();
                    } 
                }; 
                boton.addActionListener(listener);
                
                
                la.setBounds(5, 5, 53, 53);
                la.setIcon(aux.getImagen().getIcon());
                
                
                /*p.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        ModificarMouseClicked(evt, l.getText(), Integer.parseInt(num.getText()));
                    }
                });*/
                p.add(la);
                p.add(l);
                p.add(boton);
                p.setVisible(true);
                l.setVisible(true);
                la.setVisible(true);
                p.setVisible(true);
                p.repaint();
                
                Elemento.add(p);
                i = i + 80;
                aux = aux.getSiguiente();
                j = j + 1;
            }
            Elementos.setViewportView(Elemento);
            Elementos.getViewport().setView(Elemento);
            Elemento.setLayout(null);
            Elemento.setPreferredSize(new Dimension(215,i+14));
            
            Elementos.repaint();
            
            
        
            ChGoomba.setSelected(false);
            Carga.setIcon(null);
            Nombre.setText("");
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            ChCastillo.setSelected(false);
    }
    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
        //Elementos.setBackground(new Color(170, 230, 0));
        CargarObjetos();
        if(L.getInicio() != null)
        {
            Creacion.setEnabled(true);
        }
        
    }//GEN-LAST:event_CargarActionPerformed

    private void GoombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoombaMouseClicked
        // TODO add your handling code here:
        if(ChGoomba.isSelected())
        {
            ChGoomba.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChGoomba.setSelected(true);
            Carga.setIcon(LGoomba.getIcon());
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            ChCastillo.setSelected(false);
        }
    }//GEN-LAST:event_GoombaMouseClicked

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt,String a, int i) {                                    
        // TODO add your handling code here:
        LNodo aux = L.Buscar(a,i);
        if(CargaModificar.getIcon() == null)
        {
            CargaModificar.setIcon(aux.getImagen().getIcon());
            NombreModificar.setText(a);
        }else{
            CargaModificar.setIcon(null);
            NombreModificar.setText("");
        }
        
    }         
    private void KoopaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KoopaMouseClicked
        // TODO add your handling code here:
        if(ChKoopa.isSelected())
        {
            ChKoopa.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChKoopa.setSelected(true);
            Carga.setIcon(LKoopa.getIcon());
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            ChCastillo.setSelected(false);
        }
    }//GEN-LAST:event_KoopaMouseClicked

    private void FichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FichaMouseClicked
        // TODO add your handling code here:
        if(ChFicha.isSelected())
        {
            ChFicha.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChFicha.setSelected(true);
            Carga.setIcon(LFicha.getIcon());
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            ChCastillo.setSelected(false);
        }
    }//GEN-LAST:event_FichaMouseClicked

    private void HongoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HongoMouseClicked
        // TODO add your handling code here:
        if(ChHongo.isSelected())
        {
            ChHongo.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChHongo.setSelected(true);
            Carga.setIcon(LHongo.getIcon());
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChPersonaje.setSelected(false);
            ChCastillo.setSelected(false);
        }
    }//GEN-LAST:event_HongoMouseClicked

    private void PersonajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonajeMouseClicked
        // TODO add your handling code here:
        if(ChPersonaje.isSelected())
        {
            ChPersonaje.setSelected(false);
            Carga.setIcon(null);
            
        }else{
            ChPersonaje.setSelected(true);
            Carga.setIcon(LPersonaje.getIcon());
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChCastillo.setSelected(false);
        }
    }//GEN-LAST:event_PersonajeMouseClicked

    private void CastilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CastilloMouseClicked
        // TODO add your handling code here:
        if(ChCastillo.isSelected())
        {
            ChCastillo.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(true);
            Carga.setIcon(LCastillo.getIcon());
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
        }
    }//GEN-LAST:event_CastilloMouseClicked

    private void ACargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACargarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ACargarMouseClicked

    private void ChPersonajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChPersonajeItemStateChanged
        // TODO add your handling code here:
        if(!ChPersonaje.isSelected())
        {
            ChPersonaje.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(false);
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(true);
            Carga.setIcon(LPersonaje.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChPersonajeItemStateChanged

    private void ChCastilloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChCastilloItemStateChanged
        // TODO add your handling code here:
        if(!ChCastillo.isSelected())
        {
            ChCastillo.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(true);
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            
            Carga.setIcon(LCastillo.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChCastilloItemStateChanged

    private void ChParedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChParedItemStateChanged
        // TODO add your handling code here:
        if(!ChPared.isSelected())
        {
            ChPared.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(false);
            ChPared.setSelected(true);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            Carga.setIcon(LPared.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChParedItemStateChanged

    private void ChSueloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChSueloItemStateChanged
        // TODO add your handling code here:
        if(!ChSuelo.isSelected())
        {
            ChSuelo.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(false);
            ChPared.setSelected(false);
            ChSuelo.setSelected(true);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            Carga.setIcon(LSuelo.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChSueloItemStateChanged

    private void ChGoombaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChGoombaItemStateChanged
        // TODO add your handling code here:
        if(!ChGoomba.isSelected())
        {
            ChGoomba.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(false);
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(true);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            Carga.setIcon(LGoomba.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChGoombaItemStateChanged

    private void ChKoopaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChKoopaItemStateChanged
        // TODO add your handling code here:
        if(!ChKoopa.isSelected())
        {
            ChKoopa.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(false);
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(true);
            ChFicha.setSelected(false);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            Carga.setIcon(LKoopa.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChKoopaItemStateChanged

    private void ChFichaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChFichaItemStateChanged
        // TODO add your handling code here:
        if(!ChFicha.isSelected())
        {
            ChFicha.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(false);
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(true);
            ChHongo.setSelected(false);
            ChPersonaje.setSelected(false);
            Carga.setIcon(LFicha.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChFichaItemStateChanged

    private void ChHongoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChHongoItemStateChanged
        // TODO add your handling code here:
        if(!ChHongo.isSelected())
        {
            ChHongo.setSelected(false);
            Carga.setIcon(null);
        }else{
            ChCastillo.setSelected(false);
            ChPared.setSelected(false);
            ChSuelo.setSelected(false);
            ChGoomba.setSelected(false);
            ChKoopa.setSelected(false);
            ChFicha.setSelected(false);
            ChHongo.setSelected(true);
            ChPersonaje.setSelected(false);
            Carga.setIcon(LHongo.getIcon());
            Carga.repaint();
        }
    }//GEN-LAST:event_ChHongoItemStateChanged

    private void ACargar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACargar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ACargar1MouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    JFrame FrameCarga;
    JFrame FrameCreacion;
    public void setCarga(JFrame c)
    {
        FrameCarga = c;
    }
    public void setCreacion(JFrame c)
    {
        FrameCreacion = c;
    }
    private void CreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreacionActionPerformed
        // TODO add your handling code here:
        FrameCarga.dispose();
        FrameCreacion.show();
    }//GEN-LAST:event_CreacionActionPerformed

    
    public JPanel getPared(){
        return Pared;
    }
    public JPanel getSuelo(){
        return Suelo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ACargar;
    private javax.swing.JPanel ACargar1;
    private javax.swing.JLabel Carga;
    private javax.swing.JLabel CargaModificar;
    private javax.swing.JButton Cargar;
    private javax.swing.JPanel Castillo;
    private javax.swing.JCheckBox ChCastillo;
    private javax.swing.JCheckBox ChFicha;
    private javax.swing.JCheckBox ChGoomba;
    private javax.swing.JCheckBox ChHongo;
    private javax.swing.JCheckBox ChKoopa;
    private javax.swing.JCheckBox ChPared;
    private javax.swing.JCheckBox ChPersonaje;
    private javax.swing.JCheckBox ChSuelo;
    private javax.swing.JPanel Componentes;
    private javax.swing.JButton Creacion;
    private javax.swing.JPanel Elemento;
    private javax.swing.JScrollPane Elementos;
    private javax.swing.JPanel Ficha;
    private javax.swing.JPanel Goomba;
    private javax.swing.JPanel Hongo;
    private javax.swing.JPanel Koopa;
    private javax.swing.JLabel LCastillo;
    private javax.swing.JLabel LFicha;
    private javax.swing.JLabel LGoomba;
    private javax.swing.JLabel LHongo;
    private javax.swing.JLabel LKoopa;
    private javax.swing.JLabel LPared;
    private javax.swing.JLabel LPersonaje;
    private javax.swing.JLabel LSuelo;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NombreModificar;
    private javax.swing.JPanel Pared;
    private javax.swing.JPanel Personaje;
    private javax.swing.JComboBox PilaCola;
    private javax.swing.JPanel Suelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
