/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author JP
 */
public class Carga extends javax.swing.JFrame {

    /**
     * Creates new form Carga
     */
    public Carga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Componentes = new javax.swing.JPanel();
        Pared = new javax.swing.JPanel();
        ChPared = new javax.swing.JCheckBox();
        ChSuelo = new javax.swing.JCheckBox();
        Suelo = new javax.swing.JPanel();
        Elementos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Componentes.setBackground(new java.awt.Color(0, 0, 0));

        Pared.setBackground(new java.awt.Color(0, 0, 0));
        Pared.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Pared.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ParedLayout = new javax.swing.GroupLayout(Pared);
        Pared.setLayout(ParedLayout);
        ParedLayout.setHorizontalGroup(
            ParedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        ParedLayout.setVerticalGroup(
            ParedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        ChPared.setBackground(new java.awt.Color(0, 0, 0));
        ChPared.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChPared.setForeground(new java.awt.Color(255, 255, 255));
        ChPared.setText("Pared");

        ChSuelo.setBackground(new java.awt.Color(0, 0, 0));
        ChSuelo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ChSuelo.setForeground(new java.awt.Color(255, 255, 255));
        ChSuelo.setText("Suelo");

        Suelo.setBackground(new java.awt.Color(0, 0, 0));
        Suelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Suelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SueloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SueloLayout = new javax.swing.GroupLayout(Suelo);
        Suelo.setLayout(SueloLayout);
        SueloLayout.setHorizontalGroup(
            SueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        SueloLayout.setVerticalGroup(
            SueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ComponentesLayout = new javax.swing.GroupLayout(Componentes);
        Componentes.setLayout(ComponentesLayout);
        ComponentesLayout.setHorizontalGroup(
            ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComponentesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addComponent(ChSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Suelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addComponent(ChPared, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        ComponentesLayout.setVerticalGroup(
            ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentesLayout.createSequentialGroup()
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(ChPared))
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Pared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComponentesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(ChSuelo))
                    .addComponent(Suelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Elementos.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout ElementosLayout = new javax.swing.GroupLayout(Elementos);
        Elementos.setLayout(ElementosLayout);
        ElementosLayout.setHorizontalGroup(
            ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );
        ElementosLayout.setVerticalGroup(
            ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Componentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Componentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Elementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void ParedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParedMouseClicked
        // TODO add your handling code here:
        if(ChPared.isSelected())
        {
            ChPared.setSelected(false);
        }else{
            ChPared.setSelected(true);
        }
        
    }//GEN-LAST:event_ParedMouseClicked

    private void SueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SueloMouseClicked
        // TODO add your handling code here:
        if(ChSuelo.isSelected())
        {
            ChSuelo.setSelected(false);
        }else{
            ChSuelo.setSelected(true);
        }
    }//GEN-LAST:event_SueloMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Elementos.setBackground(new Color(170, 230, 0));
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public JPanel getPared(){
        return Pared;
    }
    public JPanel getSuelo(){
        return Suelo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChPared;
    private javax.swing.JCheckBox ChSuelo;
    private javax.swing.JPanel Componentes;
    private javax.swing.JPanel Elementos;
    private javax.swing.JPanel Pared;
    private javax.swing.JPanel Suelo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
